NOTIFICATION_TYPE_REGULAR = 'REGULAR'
NOTIFICATION_TYPE_SILENT_PUSH = 'SILENT_PUSH'
NOTIFICATION_TYPE_NO_PUSH = 'NO_PUSH'

ATTACHMENT_TYPE_IMAGE = 'image'
ATTACHMENT_TYPE_TEMPLATE = 'template'

TEMPLATE_TYPE_BUTTON = 'button'
TEMPLATE_TYPE_GENERIC = 'generic'

BUTTON_TYPE_WEB_URL = 'web_url'
BUTTON_TYPE_POSTBACK = 'postback'
